name: actions-in-action
description: "Run actions in action"

inputs:
  argument-one:
    description: "This is argument one"
    required: true
  argument-two:
    description: "This is argument two"
    required: false
    default: "value of argument two"

outputs:
  result:
    description: 'result of all our efforts'
    value: ${{ steps.heavy-lifting.outputs.result }}

runs:
  using: composite
  steps:
    - name: show the configuration
      shell: bash
      run: |
        echo "HI!" > hi.txt

    - name: use another action
      uses: actions/upload-artifact@v2
      with:
        name: hi
        path: hi.txt
        retention-days: 2

    - name: set some sort of output
      id: heavy-lifting
      shell: bash
      run: |
        echo "::set-output name=result::DONE"

